#!/bin/bash

ls > lista_Nombres
ls -b > lista_Cambiar
echo #!/bin/bash > cambioNombre
cantidadLineas=$(wc -l lista_Nombres | cut -d " " -f1)
echo $cantidadLineas
for (( n=1; n<=$cantidadLineas; n++ )); do 
	nombre=$(head -n $n lista_Nombres | tail -n 1 | tr ' ' '_')
	nombreACambiar=$(head -n $n lista_Cambiar | tail -n 1) 
	echo $nombreACambiar
	if [[ $nombreACambiar == $nombre ]]; then
		echo mismo nombre
	else
		echo mv  $nombreACambiar $nombre >> cambioNombre
 	        	
	fi
	
done

chmod +x cambioNombre
./cambioNombre
rm -f lista_Nombres lista_Cambiar cambioNombre

